### ISSUE TITLE
[FR] Stop automatically opening the sidebar

### ISSUE THREAD

**Issue by wwjCMP** [liolle/Crafty#3]
I hope this plugin can add an option to stop automatically opening the sidebar

**Comment by liolle** [comment]
Hi, i  should be able to add an option for that.

**Comment by gleyconJ** [comment]
I would also love to, because my computer is a notebook, and I spend more time with it closed than open.

Do you have an estimate of when this feature will be implemented?

**Comment by liolle** [comment]
Hi, @wwjCMP , @gleyconJ , i will release a new version containing that update within the next one to two days.

**Comment by liolle** [comment]
This should be fix with this [release](https://github.com/liolle/Crafty/releases/tag/1.1.0)
