### ISSUE TITLE
Rename title by edit comment.

### ISSUE THREAD

**Issue by gleyconJ** [liolle/Crafty#4]
It would be asking a lot of you if you implemented the feature of changing the name that appears on the object, to the same name that we put in "EDIT". Because I understand this add-on as a Topic Browser and often the names are of the files themselves and it looks like this:

nononon.mp4
nononono.canvas.
___________
nononon.pdf

nonono.md

And the biggest problem would be with the internet pages! Which in their case is just an empty field.

I would love to be able to change the name. Type a check box. If I click on it, the original names (like those in the example above) disappear and the text I inserted in "EDIT" takes their place. If the original names are unchecked, they remain.

And in advance, thanks for your attention.

**Comment by liolle** [comment]
Hey, @gleyconJ, I'could include the option to edit the name of a node in an upcoming release.

**Comment by gleyconJ** [comment]
Hey! Thank you very much for your attention. I would really like you to do that. Do you have an estimate of when you intend to include this feature in your plug-in?

**Comment by liolle** [comment]
I would  say this weekend

**Comment by gleyconJ** [comment]
🥳
