### ISSUE TITLE
Name web pages by title

### ISSUE THREAD

**Issue by gleyconJ** [liolle/Crafty#5]
How about Carfty copying the name of the page or its address instead of leaving an empty space in the add-on's navigation bar? Because at the current moment, objects that are www are empty.

Thank you in advance for your attention, if you fulfill my request.

**Comment by liolle** [comment]
yes, i have added the url of the web page as default for web page node, but u also can modify the title now in the new [release](https://github.com/liolle/Crafty/releases/tag/1.1.2).
@gleyconJ
